
services:
  php-pdfium:
    image: phpdfium:dev
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: base
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    volumes:
      - ./:/usr/php-pdfium
